### ISSUE TITLE
Assertion calls test twice

### ISSUE THREAD

**Issue by fabriciofx** [llorllale/cactoos-matchers#86] opened 2019-01-20 12:04 UTC
`Assertion` calls` Scalar<T> test` twice and this cause some troubles, mainly when testing the content of a stream, like:
```
Assertion(
    "The reason if fails",
    new TextOf(new InputOf(...)),
    new TextHasString("tS")
).affirm()
```
because in the first call stream will be closed. So, I think a possible solution is put a `Sticky` decorator on `Scalar<T> test` parameter. @llorllale WDYT?

**Comment by 0crat** [comment] 2019-01-20 12:04
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment] 2019-01-20 22:41
@fabriciofx this is a duplicate of #53

**Closed by llorllale** 2019-01-20 22:41 UTC

**Comment by 0crat** [comment] 2019-01-20 23:05
Job `gh:llorllale/cactoos-matchers#86` is not assigned, can't get performer

**Comment by 0crat** [comment] 2019-01-20 23:06
This job is not in scope
