### ISSUE TITLE
Examples from readme.md are incorrect as they are written for Assertion which consuming Scalar<T>

### ISSUE THREAD

**Issue by dgroup** [llorllale/cactoos-matchers#149] opened 2019-12-15 13:11 UTC
Examples from readme.md are incorrect as they are written for Assertion which consuming Scalar<T>:
*AR*:
```java
@Test
public void textHasPrefix() {
  new Assertion<>(
    "must have the prefix",
    () -> new TextOf(new File("some.log")),
    new StartsWith("Application startup")
  ).affirm();
} 
```
*ER*:
```java
@Test
public void textHasPrefix() {
  final String prefix = "Application startup";
  new Assertion<>(
    "must have the prefix",
    new TextOf(new File("some.log")),
    new StartsWith("Application startup")
  ).affirm();
} 
```

**Comment by 0crat** [comment] 2019-12-15 13:11
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment] 2019-12-17 11:22
@0crat in

**Comment by 0crat** [comment] 2019-12-17 11:23
> @0crat in ([here](https://github.com/llorllale/cactoos-matchers/issues/149#issuecomment-566500291))

@paulodamaso Job [#149](https://github.com/llorllale/cactoos-matchers/issues/149) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2019-12-17 11:31
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @dgroup[/z](https://www.0crat.com/u/dgroup)

**Comment by 0crat** [comment] 2019-12-17 11:34
The job [#149](https://github.com/llorllale/cactoos-matchers/issues/149) assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/C63314D6Z/61cd091c-3cf7-40bb-bc8d-f6646e0e4f24); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by fanifieiev** [comment] 2020-01-13 19:42
@dgroup The issue has been completed, [PR](https://github.com/llorllale/cactoos-matchers/pull/150) has been merged. Please take the further action.

**Comment by paulodamaso** [comment] 2020-01-29 02:17
@llorllale we need to close this one. I don't have permission to do it though

**Closed** 2020-01-29 02:47 UTC

**Comment by 0crat** [comment] 2020-01-29 04:11
@llorllale[/z](https://www.0crat.com/u/llorllale) the issue is closed not by @dgroup[/z](https://www.0crat.com/u/dgroup) (its creator); I won't close the order; please, re-open it and ask @dgroup[/z](https://www.0crat.com/u/dgroup) to close it

**Comment by 0crat** [comment] 2020-02-04 04:43
@fanifieiev[/z](https://www.0crat.com/u/fanifieiev) resigned from [#149](https://github.com/llorllale/cactoos-matchers/issues/149), since the job is not in scope anymore

**Comment by 0crat** [comment] 2020-02-04 05:11
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@377a78bde909, thread: PQ-C63314D6Z
com.zerocracy.claims.ClaimIn[214] java.lang.IllegalArgumentException: Parameter "age" not found in "Order was canceled" among: [reason, priority, job, cause, _parent_sig, flow, voluntarily, login]
```

[0.51.0](https://github.com/zerocracy/farm): CID: [ea05393a-7c49-41ca-adfe-978be4363e32](https://www.0crat.com/footprint/C63314D6Z/ea05393a-7c49-41ca-adfe-978be4363e32), Type: "Order was canceled"
