### ISSUE TITLE
o.l.c.m.Throws: Matcher to test that scalar is throwing exception within particular type and message

### ISSUE THREAD

**Issue by dgroup** [llorllale/cactoos-matchers#40] opened 2018-11-30 22:20 UTC
Very often during the testing, we are receiving the exception and we need to check the root cause exception in the exception's hierarchy.

```java
new AssertException(
    () -> throw new UncheckedIOException(
        new IOException(
            new Exception(
                new TimeoutException("Task can't be completed within 5 seconds")
            )
       )
   )
).hasRootcause(
    "Task can't be completed within 5 seconds"
)
// or
).hasRootcause(
    "Task can't be completed within 5 seconds", TimeoutException.class
)
```
The solution can contain two parts
1) Add a new class to `cactoos` - o.c.exception.RootCauseOf implements Scalar<Exception>
2) Add a new class to `cactoos-matchers` - o.l.c.matchers.AssertException

**Comment by 0crat** [comment] 2018-11-30 22:20
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment] 2018-12-02 21:17
@dgroup there are 2 new things here, I think:
* matcher for exceptions
* matcher for root cause of an exception

Please create separate issues for each.

**Comment by dgroup** [comment] 2018-12-04 17:35
@llorllale, i've reconsider the approach and now i suggest to implement in such way
```java
MatcherAssert.assertThat(
    () -> throw new UncheckedIOException(
        new IOException(
           new Exception(
              new TimeoutException("Task can't be completed within 5 seconds")
          )
        )
    ),
    new HasRootCause("The msg", TimeoutException.class)
)
```
where `HasRootCause` is
```java
public final class HasRootCause extends TypeSafeDiagnosingMatcher<Scalar>
```

**Comment by dgroup** [comment] 2018-12-04 17:36
Also, we can add something like `HasRootCauseMatching` where we can pass the function.

**Comment by llorllale** [comment] 2018-12-07 23:58
@dgroup what I still can't quite wrap my head around is: why should we assert on the root cause of an exception?

The behavior being tested should have its business requirements clear - I don't understand why you would want to test the cause of the exception being thrown at you.

**Comment by dgroup** [comment] 2018-12-08 02:15
@llorllale, the original idea was:
I'm developing an object and for some particular scenario, it throws the exception.
```java
public final class TheObject implements Scalar<Integer> {
    ...
    public Integer value() throws Exception {
        if(this.somethingHappens()){
            throw new IllegalArgumentException("The msg.");
        } 
        ...
   }
   ...
}
```
This scalar object can be wrapped by another scalar(s) like StrictScalar/StickyScalar/etc, thus the root cause exception might be wrapped by a hierarchy of the exceptions. This matcher should allow us to find what is the root cause of the error.

That was the original idea. Now after discussion with you, I'm starting to think that we shouldn't do that in that way as we are breaking the encapsulation (as we will know what exactly exception message and type should be thrown from the object(s) which may be composed by someone else).

In order do not break the encapsulation we need to test the exception(s) within our object `only` which we are developing. The following approach can be used here
```java
public final class TheObject implements Scalar<Integer> {
    ...
    public Integer value() throws Exception {
        if(this.somethingHappens()){
            throw new IllegalArgumentException("The msg.");
        } 
        ...
   }
   ...
}
...
MatcherAssert.assertThat(
    new TheObject(...),
    new IsThrowingException("The msg", IllegalArgumentException.class)
)
```
The `IsThrowingException` might be based on 
 - `exception instanceof IllegalArgumentException`
 -  `exception.getName()`.

I know that `instanceof` is against the `EO` ideas, but we have no other ways as this is default java exception handling procedure.

@llorllale, WDYT?

**Comment by llorllale** [comment] 2018-12-08 02:33
@dgroup I think a better name is `Throws`

**Comment by llorllale** [comment] 2018-12-08 02:33
@0crat in

**Comment by 0crat** [comment] 2018-12-08 02:34
> @0crat in ([here](https://github.com/llorllale/cactoos-matchers/issues/40#issuecomment-445423058))

@llorllale Job [#40](https://github.com/llorllale/cactoos-matchers/issues/40) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2018-12-08 02:41
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @dgroup[/z](https://www.0crat.com/u/dgroup)

**Comment by 0crat** [comment] 2018-12-08 13:34
> @0crat assign @dgroup  ([here](https://github.com/llorllale/cactoos-matchers/issues/40#issuecomment-445459142))

@llorllale The job [#40](https://github.com/llorllale/cactoos-matchers/issues/40) assigned to @dgroup[/z](https://www.0crat.com/u/dgroup), here is [why](https://www.0crat.com/footprint/C63314D6Z/868f4dae-1d85-4063-be22-92ac6ced4c77); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment] 2018-12-08 13:42
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment] 2018-12-08 13:42
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Closed** 2018-12-08 14:59 UTC

**Comment by 0crat** [comment] 2018-12-08 15:16
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment] 2018-12-08 15:20
The job [#40](https://github.com/llorllale/cactoos-matchers/issues/40) is now out of scope
